MITLibraries/transmogrifier

- README.md
- tests/conftest.py
- tests/test_cli.py
- tests/test_config.py
- tests/test_datacite.py
- tests/test_dspace_dim.py
- tests/test_dspace_mets.py
- tests/test_transformer.py
- tests/test_zenodo.py
- transmogrifier/cli.py
- transmogrifier/config.py
- transmogrifier/helpers.py
- transmogrifier/sources/datacite.py
- transmogrifier/sources/dspace_dim.py
- transmogrifier/sources/dspace_mets.py
- transmogrifier/sources/transformer.py
- transmogrifier/sources/zenodo.py
Refactors the source transforms to reduce duplication:
* Adds a base Transformer class with initialization, iteration, and next method that is common to all source transformers.
* Makes source transformers subclasses of the base Transformer and removes their now unnecessary code.
* Moves transformer selection to the config module and determines it at runtime by the static configuration of each source.
* Bases the cli source option on the configured sources to ensure that definition of possible source transforms is located in only one place.
* Adds/updates tests to reflect all changes, including cleaning up fixtures and test names.
* Removes some no-longer-needed tests to reduce duplication.
* Adds an optional env variable to adjust the transform status update interval.
Run any source …
> Refactor source transforms

- tests/fixtures/datacite/datacite_record_all_fields.xml
- tests/fixtures/datacite/datacite_record_attribute_and_subfield_variations.xml
- tests/fixtures/dspace/dspace_dim_record_attribute_variations.xml
- tests/fixtures/dspace/dspace_mets_record_attribute_and_subfield_variations.xml
- tests/test_datacite.py
- tests/test_dspace_dim.py
- tests/test_dspace_mets.py
- transmogrifier/sources/datacite.py
- transmogrifier/sources/dspace_dim.py
- transmogrifier/sources/dspace_mets.py
Adds tests and updates source transform logic to ensure all expected variations of source XML subelements and attributes are handled.
To verify that it works on records that previously threw an error, run the transform locally against the latest Zenodo "full" harvest on stage (must be logged into stage with the MITDevelopersLimited role), e.g.:
```
pipenv run transform -i s3://timdex-extract-stage-840055183494/zenodo-full-harvested-records-2022-07-20.xml -o output/zenodo-transformed-records.json -s zenodo
```
- https://mitlibraries.atlassian.net/browse/RDI-233
NO
- **NA** All new ENV is documented in README
> Update subfield logic and tests across sources

- tests/fixtures/dspace/dspace_dim_record_all_fields.xml
- tests/fixtures/dspace/whoas_records_with_valid_and_invalid_content_types.xml
- tests/test_dspace_dim.py
- tests/test_whoas.py
- tests/test_zenodo.py
- transmogrifier/sources/dspace_dim.py
- transmogrifier/sources/whoas.py
- transmogrifier/sources/zenodo.py
Updates the WHOAS and Zenodo content type filters based on stakeholder feedback.
I've re-ingested the WHOAS and Zenodo records from the dev deployment of this code in AWS, so you can verify by going to the [RDI UI](https://rdi.libraries.mit.edu/) and confirming that:
- There are no longer any WHOAS records with "Not specified", "Other", or "Text" content types _unless_ the record also has a content type we do ingest, such as dataset, image, etc.
- Only records with any of the following content types are present in Zenodo records _unless_ the record also has a content type we do ingest (one of these): dataset, image, other, physicalobject, software, video, taxonomictreatment, diagram, drawing, figure, photo, plot
NO
- https://mitlibraries.atlassian.net/browse/RDI-243
- …
> Update WHOAS and Zenodo content type filters

- config/aspace_type_crosswalk.json
- tests/fixtures/ead/ead_record_all_fields.xml
- tests/fixtures/ead/ead_record_attribute_and_subfield_variations.xml
- tests/fixtures/ead/ead_record_blank_optional_fields.xml
- tests/test_ead.py
- transmogrifier/sources/ead.py
Run the transform locally using the `aspace-full-harvested-records-2022-08-19.xml` file in the dev S3 bucket, e.g.:
```
pipenv run transform -i <S3 URL for file above> -o aspace-timdex.json -s aspace
```
https://mitlibraries.atlassian.net/browse/TIMX-64
NO
> TIMX-64-expand-get-optional-fields

- tests/fixtures/ead/ead_record_all_fields.xml
- tests/fixtures/ead/ead_record_attribute_and_subfield_variations.xml
- tests/fixtures/ead/ead_record_blank_optional_fields.xml
- tests/test_ead.py
- transmogrifier/sources/ead.py
Run the transform locally using the `aspace-full-harvested-records-2022-08-19.xml` file in the dev S3 bucket, e.g.:
```
pipenv run transform -i <S3 URL for file above> -o aspace-timdex.json -s aspace
```
* https://mitlibraries.atlassian.net/browse/TIMX-64
NO
> TIMX-64-complete-get-optional-fields

- tests/fixtures/marc/marc_record_all_fields.xml
- tests/fixtures/marc/marc_record_attribute_and_subfield_variations.xml
- tests/fixtures/marc/marc_record_blank_optional_fields.xml
- tests/test_marc.py
- transmogrifier/sources/marc.py
I'm getting this PR out for review while I'm out since there is no overlap with the code changes in PR #36. While there shouldn't be any major merge conflicts with PR #36, I'll rebase this branch after #36 is approved and merged to take care of any that may arise.
Run the transform locally using the `alma-2022-10-11-full-extracted-records-to-index.xml` file in the dev S3 bucket, e.g.:
```
pipenv run transform -i <S3 URL for the above file> -o alma-transformed-records.json -s alma
```
* https://mitlibraries.atlassian.net/browse/TIMX-18
NO
> TIMX-18-marc-transform-even-more-fields

- tests/fixtures/oai_pmh_records.xml
- tests/fixtures/record_deleted.xml
- tests/test_transformer.py
- transmogrifier/sources/transformer.py
Adds functionality to skip deleted records during transform so they don't raise errors. This is a temporary solution until we're ready to add actual deleted record handling.
Run a transform on the latest ASpace daily update file, which includes two deleted records (aspace-2022-11-30-daily-extracted-records-to-index.xml in the dev S3 bucket):
```
pipenv run transform -i <path-to-file-above> -o output/aspace-transform.json -s aspace
```
There should be 6 total records processed, 4 transformed and 2 skipped.
- https://mitlibraries.atlassian.net/browse/TIMX-126
NO
> Skip deleted records during transform

- transmogrifier/helpers.py
Changes the file open mode for helpers.write_deleted_records_to_file() to write.
Due to current weirdness with the Alma records, the deleted records output file was opened in append mode to ensure we didn't overwrite deleted records that may show up in the wrong export file. However, smart_open doesn't implement append mode in its open() function with S3 files so this needs to revert to write mode.
Deleted records during Alma export may not be 100% accurate until the current Alma record export issue is fixed. The metadata team is working on it and we will just have to do a full re-ingest once that's done to ensure we have accurate data in TIMDEX.
> Fix file open bug for s3

- tests/fixtures/marc/marc_record_all_fields.xml
- tests/fixtures/marc/marc_record_attribute_and_subfield_variations.xml
- tests/test_marc.py
- transmogrifier/sources/marc.py
In the MARC transform, adds locations from which to pull the URL for electronic portfolio item holdings and also adds those URLs as links.
View the original items with no link in our [prod timdex playground](https://timdex.mit.edu/playground), query:
```
{
search(searchterm: "graphql oreilly") {
records {
title
sourceLink
links {
text
url
kind
}
}
}
}
```
And then view the same search results in our [dev timdex ui](https://timdex-ui-pipeline-dev.herokuapp.com/results?q=graphql+oreilly&advanced=&citation=&contributors=&fundingInformation=&identifiers=&locations=&subjects=&title=), which have been re-ingested with the new mappings (click on individual items to see the links and holdings fields populated with the e-resource links).
NO
- https://mitlibraries.atlassian.net/browse/TIMX-184
> Re-map MARC portfolio items to holdings and links

- transmogrifier/sources/transformer.py
Replaces recursive call in the Transformer class `__next__` method with an internal loop.
The Transformer's internal `__next__` method used recursion to skip over records that couldn't be transformed, which was both inefficient and hit a recursion depth limit while processing deletes (none of which are transformed).
On the current main branch, try to transform the Alma file that was causing issues and you should hit the same error we did on prod (I copied the file to Dev1 for easier testing):
```
pipenv run transform -i s3://timdex-extract-dev-222053980223/alma/alma-2023-03-07-daily-extracted-records-to-delete.xml -o output/alma-deletes.json -s alma
```
Then checkout this branch and run the same transform. It should complete successfully.
NO
> Fix recursion bug

- tests/test_helpers.py
- transmogrifier/config.py
- transmogrifier/helpers.py
- transmogrifier/sources/datacite.py
- transmogrifier/sources/dspace_dim.py
- transmogrifier/sources/dspace_mets.py
- transmogrifier/sources/ead.py
- transmogrifier/sources/marc.py
Though `Marc` is the transform most likely to encounter this issue, I updated the date processing for all of the transforms. Let me know if this overkill.
I uploaded a file with a whitespace date to dev1. Run the following command on `main` to see that the whitespace is in the output and then with `date-whitespace-bug-fix` to see that the date appears without whitespace:
```
pipenv run transform -i s3://timdex-extract-dev-222053980223/alma/date-error.xml -o output/date-error-transformed-records.json -s alma
```
NO
> date-whitespace-bug-fix

- tests/fixtures/ead/ead_record_attribute_and_subfield_variations.xml
- tests/test_ead.py
- tests/test_helpers.py
- transmogrifier/helpers.py
- transmogrifier/sources/ead.py
After reviewing all the transforms, `Ead` appears to be the only one that was affected by this bug.
Before pulling down the new branch, run the following command with `main` while authenticated to dev:
```
pipenv run transform -i s3://timdex-extract-dev-222053980223/aspace/aspace-2023-10-17-full-extracted-records-to-index.xml -o output/aspace-records.json -s aspace
```
Check record `aspace:repositories-2-resources-531` and see the invalid date. 
Fetch `TIMX-212-invalid-date-fix` and run the same command to see that the invalid date has been omitted.
* https://mitlibraries.atlassian.net/browse/TIMX-212
NO
> TIMX-212-invalid-date-fix

- Makefile
- Pipfile.lock
- transmogrifier/cli.py
- transmogrifier/helpers.py
_NOTE: reworking of PR https://github.com/MITLibraries/transmogrifier/pull/95 with convention branch name_
While onboarding and reading through the codebase to understand how it works, I found myself tripping on a variable name and type in the `helpers.write_timdex_records_to_json` function that the CLI calls.
It looks as though sometime last year, the `Transformer` class had an interator pattern introduced that slightly changed downstream types.  Instead of passing an iterator of records, an actual `Transformer` instance is passed, where calling `next(transformer_instance)` will produce a _transformed_ record.
No changes to functionality of code, just type hints.
Can confirm that all testing and linting passes:
```bash
make test
make lint
```
And, can confirm via built-in type hinting …
> Update type hints in helpers.write_timdex_records_to_json

- Pipfile.lock
- tests/fixtures/ead/ead_record_attribute_and_subfield_variations.xml
- tests/test_ead.py
- transmogrifier/sources/ead.py
For ASpace records, any `<unitid type="aspace_uri">` elements are skipped for consideration as TIMDEX record `identifiers`.  
It was discovered that some ASpace records after transformation contained multiple identifiers, of the same type, which was throwing errors in Bento.  It looks as though ASpace records may have changed slightly and are exposing a new string for the <unitid> element, which is the same as the OAI record identifier.
Before:
After:
Run the following transform:
```bash
pipenv run transform -s aspace -i tests/fixtures/ead/ead_record_attribute_and_subfield_variations.xml -o output/aspace-ead-single-identifier.json
```
- observe that `identifiers` property only has a single value, despite two `<unitid>` elements present under `<archdesc level="collection">` …
> Why these changes are being introduced:

- Pipfile
- Pipfile.lock
- tests/fixtures/ead/ead_record_all_fields.xml
- tests/fixtures/ead/ead_record_attribute_and_subfield_variations.xml
- tests/test_ead.py
- transmogrifier/sources/ead.py
This PR udpates the logic for how dates are parsed for ASpace EADs.
Nearly all (~96%) ASpace EADs have a `@normal` attribute in the `archdesc.unitdate` element that is normalized and predictable in form.  This value is used now, split on `/` for date ranges, to populate dates for the TIMDEX record.
Other changes:
* dependencies updated
* `ipython` added as `--dev` package
We receieved a Sentry error that a record had an invalid date range.  As described in the linked ticket, it became apparent this was related to a combination of date parsing and validation, and how it varies between Transmogrifier and OpenSearch environments.
It has been noted in the linked Jira tickets that the EAD unitdate field @normal attribute might contain a more normalized form of the date that could help with …
> TIMX-235 Update ASpace EAD date parsing

- Pipfile.lock
- tests/test_oai_dc.py
- tests/test_springshare.py
- transmogrifier/sources/oaidc.py
- transmogrifier/sources/springshare.py
Sets `date.kind` property for Springshare and generic OAI-DC transformers.
It was discovered that setting `date.kind = None` was throwing errors in GraphQL, which prevented the `date` field from coming through:
```json
{
"data": {
"search": {
"hits": 1,
"records": [
{
"timdexRecordId": "libguides:guides-1336858",
"title": "Affirmative Action",
"source": "LibGuides",
"dates": null
}
]
}
},
"errors": [
{
"message": "Cannot return null for non-nullable field Date.kind"  #<---------------
}
]
}
```
While the Springshare OAI records don't have any additional metadata about the `<dc:date>` fields, it was determined that they must be "Created" as they don't change across modifications to the resource.
Run libguides transformation:
```shell
pipenv run transform -s libguides -i …
```
> Timx 241 springshare oai dates

- tests/fixtures/aardvark_records.jsonl
- tests/sources/json/test_aardvark.py
- transmogrifier/sources/json/aardvark.py
After an MITAardvark transformation was mostly completed, a couple of small bugs were discovered when attempting to index the transformed TIMDEX records into OpenSearch.  This commit adddresses those bugs, both full fixes and workarounds, to allow continued pipeline testing and improvements to the MITAardvark transformation.
How this addresses that need:
* adds `kind` property to Dates and Identifiers
* uses `locations.value` instead of `locations.geodata`
Not readily testable as the StepFunction pipeline is not fully formed to attempt indexing of these documents.  But, these changes have been confirmed via a local solution that applied these updates to the transformation process, then successfully indexed documents into OpenSearch.
- https://mitlibraries.atlassian.net/browse/GDT-54
(not …
> GDT-54 Address mismatches with OpenSearch mapping

- docs/adrs/0004-field-for-institution-information.md
This PR introduces a new Architecture Decision Record (ADR) that proposes to add a new `institution` field to the TIMDEX data model.
This discussion was kicked off when seeking to understand what TIMDEX fields to use for displaying the host institution on GeoData's "result" and "full record" pages for non-MIT GIS resources.
NO
YES
* https://mitlibraries.atlassian.net/browse/GDT-205
> Create ADR to propose new field for host institution

- docs/adrs/0002-field-for-data-type-form-information.md
This PR introduces a new Architecture Decision Record (ADR) that proposes to add a new `form` field to the TIMDEX data model.  
This discussion was kicked off when seeking to understand what TIMDEX fields to use for facet filters in a new geospatial TIMDEX UI.  Reaching a decision on where to store this data in a TIMDEX record will unblock work for DataEng (work to store the data) and EngX (utilize the data for facets).
Rendered markdown for current version of the ADR: https://github.com/MITLibraries/transmogrifier/blob/GDT-193-adr-handle-data-forms/docs/adrs/0002-field-for-data-type-form-information.md
NO
NO
- https://mitlibraries.atlassian.net/browse/GDT-193
> ADR to handle dataset information in TIMDEX

- Pipfile.lock
- tests/sources/json/test_aardvark.py
- transmogrifier/sources/json/aardvark.py
Implementing the decision described in [ADR #2](https://github.com/MITLibraries/transmogrifier/blob/main/docs/adrs/0002-field-for-data-type-form-information.md)
Run the following command and observe that `Vector data` appears in `content_type`:
```
pipenv run transform -o output/gismit.json -i  tests/fixtures/aardvark/aardvark_record_all_fields.jsonl -s gismit
```
YES
YES
- https://mitlibraries.atlassian.net/browse/GDT-201
> Gdt 201 data type refactor

- tests/sources/json/test_aardvark.py
- transmogrifier/models.py
- transmogrifier/sources/json/aardvark.py
Add a top-level field `provider` to the TIMDEX data model and derive values for GIS sources (i.e., `gismit` and `gisogm` via the `MITAardvark` transformer). This field represents the institution or organization that provides access to the resource represented in TIMDEX.  This change came from the need to support a UI filter "Institution" for the GeoData website and implements the decision proposed in [ADR-0004](https://github.com/MITLibraries/transmogrifier/blob/main/docs/adrs/0004-field-for-institution-information.md).
Note a couple things:
* This PR only adds the derivation of `provider` for GIS sources. 
* There are suggestions in ADR-004 on deriving this field for multiple sources might improve from changing their mapping to utilize this field, but before changes are made they are …
> Add "provider" field to TIMDEX and derive values for GIS sources

- .adr-dir
- docs/adrs/0003-support-aggregations-on-publisher-name.md
also adds config to allow adr cli to create an adr in the same directory other adrs are found in this repository
https://mitlibraries.atlassian.net/browse/GDT-199
Rendered markdown of current ADR: https://github.com/MITLibraries/transmogrifier/blob/gdt-199-publication-adr/docs/adrs/0003-support-aggregations-on-publisher-name.md
NO
YES
> Adds ADR for remapping PublicationInformation

- tests/sources/test_transformer.py
- transmogrifier/sources/transformer.py
Map `Aardvark.dct_spatial_sm` to `Locations@kind="Place Name"` to support the use of place names
for location-based searching for GeoData. 
**Note:** `MITAardvark` is the only source transformer that writes `Subject@kind="Dublin Core; Spatial"` (i.e., what `Aardvark.dct_spatial_sm` currently maps to), so the updated mapping is only applied to this transformer.
1. Temporarily set AWS credentials for `TimdexManagers` for `Dev1` in your terminal.
2. Transform `gismit` records
* Run the following command from your local clone of `transmogrifier`:
```
pipenv run transform -i s3://timdex-extract-dev-222053980223/gismit/gismit-2024-03-11-full-extracted-records-to-index.jsonl -o output/output_gismit.json -s gismit -v
```
* View `output/output_gismit.json`. Lines 67-88 should read:
3. Transform …
> Map Aardvark.dct_spatial_sm to Locations@kind="Place Name"

- tests/sources/test_transformer.py
- transmogrifier/sources/transformer.py
An error was encountered when trying to run the latest updates to the transformer against the full `gisogm` source:
```
File "/Users/jcuerdo/Documents/repos/transmogrifier/transmogrifier/sources/transformer.py", line 256, in _transform
fields = self.create_locations_from_spatial_subjects(fields)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/jcuerdo/Documents/repos/transmogrifier/transmogrifier/sources/transformer.py", line 417, in create_locations_from_spatial_subjects
if subject_location not in fields.setdefault("locations", []):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```
When a field method returns `None` values (resulting from `or None` statements), the `fields` dictionary will be populated …
> Update post-transform methods to handle None values

- docs/adrs/0005-field-methods.md
ADR for discussion of a field method refactor
NO
NO
* https://mitlibraries.atlassian.net/browse/TIMX-275
> Field method ADR

- transmogrifier/exceptions.py
- transmogrifier/helpers.py
- transmogrifier/sources/transformer.py
- transmogrifier/sources/xml/datacite.py
Adding more explicit flow control through exception handling in the `Transformer` class. Previously, records were skipped when `get_optional_fields` returned `None`. Adding a `SkippedRecordEvent` exception that can handle records that should be skipped for an invalid `content_type` or records with significant structural issues that raise the risk of unknown exceptions later in the process. This is a minor update to the orchestration that should aid us with the field method refactor.
As we proceed with the refactor in other transforms, use the `SkippedRecordEvent` exception whenever `get_optional_fields` returns `None`. Logging can be added as necessary depending on what triggered the skip.
The `Datacite` class was updated to raise  the`SkippedRecordEvent` exception illustrating that tests …
> Update exception handling

- tests/conftest.py
- tests/fixtures/datacite/datacite_record_all_fields.xml
- tests/sources/xml/test_datacite.py
- transmogrifier/sources/xml/datacite.py
Refactors the first set of `Datacite` fields as separate field methods. As this is the first of many of these PRs that DataEng will be writing/reviewing, I encourage nit-picking so we can refine the overall approach early.
Run the following command to see that the `Datacite` transform still transforms a source file:
```
pipenv run transform -i tests/fixtures/datacite/datacite_records.xml -o output/datacite-transformed-records.json -s jpal
```
NO
NO
- https://mitlibraries.atlassian.net/browse/TIMX-284
> Add 1st set of Datacite field methods

- tests/sources/xml/test_datacite.py
- transmogrifier/sources/xml/datacite.py
Continue refactoring `Datacite` transform to use field methods.
Run the following command to see that the `Datacite` transform still transforms a source file:
```
pipenv run transform -i tests/fixtures/datacite/datacite_records.xml -o output/datacite-transformed-records.json -s jpal
```
NO
NO
* https://mitlibraries.atlassian.net/browse/TIMX-284
> Add 2nd set of Datacite field methods

- tests/sources/xml/test_datacite.py
- transmogrifier/sources/xml/datacite.py
Finish refactoring `Datacite` transform to use field methods.
Run the following command to see that the `Datacite` transform still transforms a source file:
```
pipenv run transform -i tests/fixtures/datacite/datacite_records.xml -o output/datacite-transformed-records.json -s jpal
```
NO
NO
- https://mitlibraries.atlassian.net/browse/TIMX-284
> Add final set of Datacite field methods

- tests/sources/xml/test_ead.py
- transmogrifier/sources/xml/ead.py
Field method refactor for transform class Ead (Part 3).
* Add field methods and corresponding unit tests for: `languages`, `locations`, `notes`,
`physical description`, `publishers`, and `summary`
```
pipenv run transform -i tests/fixtures/ead/ead_record_all_fields.xml -o output/ead-transformed-records.json -s aspace
```
Output: 
```
2024-06-03 12:17:26,897 INFO transmogrifier.cli.main(): Logger 'root' configured with level=INFO
2024-06-03 12:17:26,897 INFO transmogrifier.cli.main(): No Sentry DSN found, exceptions will not be sent to Sentry
2024-06-03 12:17:26,897 INFO transmogrifier.cli.main(): Running transform for source aspace
2024-06-03 12:17:26,914 WARNING …
```
> Timx 287 ead field method refactor 3

- tests/sources/xml/test_ead.py
- transmogrifier/sources/xml/ead.py
Field method refactor for transform class Ead (Part 3).
* Add field methods and corresponding unit tests for: `rights`, `related_items`, and `subjects`
```
pipenv run transform -i tests/fixtures/ead/ead_record_all_fields.xml -o output/ead-transformed-records.json -s aspace
```
Output: 
```
2024-06-06 15:43:31,737 INFO transmogrifier.cli.main(): Logger 'root' configured with level=INFO
2024-06-06 15:43:31,737 INFO transmogrifier.cli.main(): No Sentry DSN found, exceptions will not be sent to Sentry
2024-06-06 15:43:31,737 INFO transmogrifier.cli.main(): Running transform for source aspace
2024-06-06 15:43:31,756 WARNING transmogrifier.sources.transformer.get_valid_title(): Record repositories/2/resources/1 has …
```
> Field method refactor for Ead transform

- tests/fixtures/dspace/dspace_mets_record_all_fields.xml
- tests/fixtures/dspace/dspace_mets_record_attribute_and_subfield_variations.xml
- tests/fixtures/dspace/dspace_mets_record_optional_fields_blank.xml
- tests/fixtures/dspace/dspace_mets_record_optional_fields_missing.xml
- tests/sources/xml/test_datacite.py
- tests/sources/xml/test_dspace_mets.py
- transmogrifier/sources/xml/dspace_mets.py
Refactors the first set of `DspaceMets` fields as separate field methods. The absurd line count is from updating the METS fixtures and updating the imports for `test_datacite.py` to bring it in line with the other unit test modules in the repo. The actual code changes are ~250 lines.
Run the following command to see that the `DspaceMets` transform still transforms a source file:
```
pipenv run transform -i tests/fixtures/dspace/dspace_mets_records.xml -o output/dspace-mets-transformed-records.json -s dspace
```
NO
NO
- https://mitlibraries.atlassian.net/browse/TIMX-286
> Add 1st set of DspaceMets field methods

- tests/sources/xml/test_dspace_mets.py
- transmogrifier/sources/xml/dspace_mets.py
Finish refactoring `DspaceMets` transform to use field methods. Just under our suggested limit 😬 
Run the following command to see that the `DspaceMets` transform still transforms a source file:
```
pipenv run transform -i tests/fixtures/dspace/dspace_mets_records.xml -o output/dspace-mets-transformed-records.json -s dspace
```
NO
NO
- https://mitlibraries.atlassian.net/browse/TIMX-286
> Add final set of DspaceMets field methods

- tests/sources/xml/test_dspace_dim.py
- transmogrifier/sources/xml/dspace_dim.py
- transmogrifier/sources/xml/whoas.py
Refactors the first set of `DspaceDim` fields as separate field methods. 
Run the following command to see that the `DspaceDim` transform still transforms a source file and skips an invalid content type according to the `Whoas` transform:
```
pipenv run transform -i tests/fixtures/dspace/dspace_dim_records.xml -o output/dspace-transformed-records.json -s whoas
```
NO
NO
* https://mitlibraries.atlassian.net/browse/TIMX-282
> Add 1st set of DspaceDim field methods

- tests/sources/json/test_aardvark.py
- tests/sources/test_transformer.py
- tests/sources/test_xmltransformer.py
- transmogrifier/sources/json/aardvark.py
Refactors the first set of `Aardvark` field methods to align with the conventions developed since this class was initially created.
Run the following command to see that the `Aardvark` class transform still transforms a source file:
```
pipenv run transform -o output/gismit.json -i  tests/fixtures/aardvark_record_all_fields.jsonl -s gismit
```
NO
NO
- https://mitlibraries.atlassian.net/browse/TIMX-285
> Timx 285 aardvark fmr

- Pipfile.lock
- tests/sources/json/test_aardvark.py
- tests/sources/test_xmltransformer.py
- tests/test_config.py
- tests/test_helpers.py
- transmogrifier/sources/json/aardvark.py
- transmogrifier/sources/xml/whoas.py
- transmogrifier/sources/xmltransformer.py
Refactors remaining `Aardvark` field methods to align with the conventions developed since this class was initially created.
Run the following command to see that the Aardvark class transform still transforms a source file:
```
pipenv run transform -o output/gismit.json -i  tests/fixtures/aardvark/aardvark_record_all_fields.jsonl -s gismit
```
NO
NO
- https://mitlibraries.atlassian.net/browse/TIMX-285
> Complete Aardvark field method refactor

- Pipfile.lock
- tests/sources/xml/test_marc.py
- transmogrifier/sources/xml/marc.py
Field method refactor for transform class `MARC` (Part 1).
* Added private methods for key elements in MARC-formatted XML records (`<leader>`, `<controlfield tag="008">`(
* Added field methods and corresponding unit tests for `alternate_titles` and `call_numbers`.
Note(s): 
* For the time-being, I've added calls to the private methods at the beginning of `get_optional_fields()`, which is required by field derivations (that will eventually be moved into their own field methods).
* The name `get_control_field_general_info` was chosen over `get_fixed_length_data` as there are technically _multiple_ fixed length fields in MARC. The fixed length field that MARC depends on is for [code 008, which describes "general information" about the …
> Timx 288 marc field method refactor

- tests/sources/xml/test_marc.py
- transmogrifier/sources/xml/marc.py
Field method refactor for transform class `Marc` (Part 2).
* Added field methods and corresponding unit tests for the following fields: [`content_type`, `contents`, `contributors`, `dates`, `editions`, `holdings`, `links`].
**Note:** Links are derived from `holdings` for electronic items, so creating a field method for `holdings` required creating a field method for `link` (to pass unit tests). 
```
pipenv run transform -i tests/fixtures/marc/marc_record_all_fields.xml -o output/marc-transformed-records.json -s alma
```
Output: 
```
2024-07-24 13:06:08,055 INFO transmogrifier.cli.main(): Logger 'root' configured with level=INFO
2024-07-24 13:06:08,055 INFO transmogrifier.cli.main(): No Sentry DSN found, …
```
> Timx 288 marc field method refactor 2

- tests/sources/xml/test_marc.py
- transmogrifier/sources/xml/marc.py
Field method refactor for transform class `Marc` (Part 3).
* Added field methods and corresponding unit tests for the following fields: [`identifiers`, `languages`, `literary_form`, `locations`, `notes`]
**Note(s)**
1. The [new `get_locations` field method correctly retrieves the characters 008/15-17](https://github.com/MITLibraries/transmogrifier/pull/202/files#diff-58573f6e57860b560075cbe825c45aace3f2830bb51d47f8d8dbf4b1b0b5d5ebR832); the [old code previously only retrieved characters 008/15-16, effectively ignoring `timdex.Location(kind="Place of Publication")` for records with 3-letter codes](https://github.com/MITLibraries/transmogrifier/pull/202/files#diff-58573f6e57860b560075cbe825c45aace3f2830bb51d47f8d8dbf4b1b0b5d5ebL171). …
> Timx 288 marc field method refactor 3

- tests/sources/xml/test_marc.py
- transmogrifier/sources/xml/marc.py
Field method refactor for transform class Marc (Part 4).
Added field methods and corresponding unit tests for the following fields: [`numbering`, `physical_description`, `publication_frequency`, `publishers`, `related_items`, `subjects`, `summary`].
As of this PR, all optional fields now have field methods. A final PR for tidying / cleanup will follow.
```
pipenv run transform -i tests/fixtures/marc/marc_record_all_fields.xml -o output/marc-transformed-records.json -s alma
```
Output: 
```
2024-07-30 10:37:44,721 INFO transmogrifier.cli.main(): Logger 'root' configured with level=INFO
2024-07-30 10:37:44,721 INFO transmogrifier.cli.main(): No Sentry DSN found, exceptions will not be sent to Sentry
2024-07-30 …
```
> Timx 288 marc field method refactor 4

- transmogrifier/sources/xml/marc.py
Field method refactor for transform class Marc (Part 5).
This PR concludes the field method refactor updates for Marc. The changes introduced this PR are minor, tidying changes meant to improve code readability. Of note is the replacing the use of dictionaries when defining MARC field mappings with tuples, allowing us to assign helpful variable names to the tuple values in the `for loop`.
```
pipenv run transform -i tests/fixtures/marc/marc_record_all_fields.xml -o output/marc-transformed-records.json -s alma
```
Output: 
```
2024-08-01 13:20:43,961 INFO transmogrifier.cli.main(): Logger 'root' configured with level=INFO
2024-08-01 13:20:43,961 INFO transmogrifier.cli.main(): No Sentry DSN found, exceptions will …
```
> Timx 288 marc field method refactor 5

- tests/test_models.py
- transmogrifier/models.py
Add a global dedupe method using `attrs` converters to remove duplicated data in `TimdexRecord` fields that comprise of item lists. The following approach was taken:
* Define an `attrs` converter method to dedupe list of items
* [Converter](https://www.attrs.org/en/stable/init.html#converters) methods can be used to normalize values as they are assigned to an `attrs` class attribute.
* A [`dedupe` method](https://github.com/MITLibraries/transmogrifier/pull/206/files#diff-62380015f300f79c3d62063c1dffd2c085e0ea5a1cfbf24946e5bb31c36d587cR38-R41) is defined. The method accepts an `item_list` and uses `list(dict.fromkeys(item_list))` to remove duplicates **while retaining the order of items** as they were passed into the list. 
* [Create a `ListField` abstract class with a `__hash__` …
> Timx 332 dedupe function

- pyproject.toml
- tests/sources/xml/test_marc.py
- transmogrifier/sources/xml/marc.py
MARC record `alma:9935219630906761` has come through Transmogrifier a handful of times where control field 008 is not 34 characters, and therefore throws an error when we attempt to grab the 33rd character.  This stops the Transmogrifier run completely.
How this addresses that need:
* If control field 008 is < 34 chars, return `None` for literary form
Side effects of this change:
* Transmogrifier runs for large swaths of files, e.g. full runs, will not catastrophically fail for this single bug.
* This might suggest another layer of error handling to avoid full run failure for a single record, will create at ticket for this.
New test `test_get_literary_form_returns_none_if_control_field_too_short` tests this edge case.
If interested, the file in production S3 …
> Address liteary form control field bug

- config/holdings_location_crosswalk.json
Adds new physical holdings location `POPUPVINYL` / `"Pop-Up Vinyl Collection"`.
To my knowledge, we don't have any records with this location yet, but confirmed it'll follow the same tag + subfield combination for other locations we crosswalk, so should get picked up and used when those records start coming through.
NO
NO
- https://mitlibraries.atlassian.net/browse/TIMX-400
> TIMX400 - new POPUPVINYL holdings location

- README.md
- tests/conftest.py
- tests/sources/test_transformer.py
- tests/test_cli.py
- transmogrifier/cli.py
- transmogrifier/sources/transformer.py
As we move into Transmogrifier writing to a parquet dataset, one important bit of information it will need is the concept of a "run id".  This correlates directly to an "Execution UUID" that every StepFunction invocation produces.  This identifier is then used when writing the records to the parquet dataset, allowing for quick and easy access to records associated with that identifier.
There is a small many-to-one relationship that makes naming a bit awkward: each StepFunction invocation may run Transmogrifier multiple times (e.g. multiple input files).  Each time it invokes Transmogrifier, the same `run_id` would be passed.  This effectively groups the outputs of all Transmogrifier invocations under the same `run_id` partition in the parquet dataset.  The language of this new `run_id` in …
> TIMX 403 - Add "run_id" CLI argument and Transformer attribute

- config/holdings_location_crosswalk.json
Similar to recent [PR 209 / TIMX-440](https://github.com/MITLibraries/transmogrifier/pull/209/files), an additional alma holdings location crosswalk is needed for `DVD / "DVDs Collection"`.
**NOTE**: to establish this in production, a tagged release will be required.  This is the first tagged release that will include the parquet dataset v1/v2 feature flagging in this application.  This has been successfully tested in stage at this point, so not worried about a production deploy, but feels noteworthy.
NO
NO
- https://mitlibraries.atlassian.net/browse/TIMX-447
> TIMX 447 - add DVDs collection location crosswalk

- Pipfile
- Pipfile.lock
This "unpins" the `timdex-dataset-api` (TDA) library from a specific release version, and instead builds from `main`.  
This recent run of the v2 StepFunction in Dev1 demonstrates that the TDA library installed is functional.  
Note also the [hash of `timdex-dataset-api` installed via the `Pipfile.lock` (`e1c0c6a894b40be4f900ebc2f01ed354e2cead41`)](https://github.com/MITLibraries/transmogrifier/pull/223/files#diff-a86c67a0a29ed0e95909b9b7c420140f302d17399ee6dcce4e1a51a14d27fd51L517-R517).  When we omit any specific references for install, and it just uses `main`, it gets the [most recent commit (`e1c0c6a894b40be4f900ebc2f01ed354e2cead41`)](https://github.com/MITLibraries/timdex-dataset-api/commit/e1c0c6a894b40be4f900ebc2f01ed354e2cead41).
YES
NO
- None
> Install timdex-dataset-api library from main

- Pipfile.lock
- tests/sources/test_transformer.py
- transmogrifier/models.py
- transmogrifier/sources/transformer.py
This PR adds the field `timdex_provenance` to the TIMDEX data model.  As outlined in the [original engineering plan](https://mitlibraries.atlassian.net/wiki/spaces/IN/pages/4094296066/Engineering+Plan+Parquet+Datasets+for+TIMDEX+ETL#Record-Provenance), this addition to TIMDEX records has multiple uses:
1. providing quick, human readable information about the record's origins (e.g. `run_date`)
2. embed enough information in the indexed Opensearch record to efficiently find the record in the parquet dataset
As outlined in a [recent `timdex-dataset-api` PR](https://github.com/MITLibraries/timdex-dataset-api/pull/73), we need to know a few things to quickly retrieve a record from the dataset: `[run_date, run_type, timdex_record_id, run_record_offset]` where `timdex_record_id` is actually kind …
> TIMX 406 - add provenance data to transformed records

- tests/conftest.py
- tests/test_cli.py
Fully remove `ETL_VERSION` env var from testing.
NO
NO
- None
> Fully remove ETL_VERSION

- tests/fixtures/ead/ead_record_all_fields.xml
- tests/fixtures/ead/ead_record_attribute_and_subfield_variations.xml
- tests/fixtures/ead/ead_record_blank_optional_fields.xml
- tests/fixtures/ead/ead_record_missing_archdesc.xml
- tests/fixtures/ead/ead_record_missing_archdesc_did.xml
- tests/fixtures/ead/ead_record_missing_optional_fields.xml
- tests/sources/xml/test_ead.py
- transmogrifier/sources/transformer.py
- transmogrifier/sources/xml/ead.py
Updates the EAD transformer to handle OAI identifiers with one or two forward slashes in the identifier, e.g.:
- `oai:mit//repository:42`
- `oai:mit/repository:42`
Where the extracted TIMDEX identifier should be `repository:42` for both.
As noted in [TIMX-501](https://mitlibraries.atlassian.net/browse/TIMX-501), this change in the OAI output was from an ASpace 4.x upgrade, is approved by ASpace stakeholders, and will remain the output going forward.  But FWIW, this regex change will handle _either_ situation.
Not much to see!  [This line from an EAD test](https://github.com/MITLibraries/transmogrifier/blob/TIMX-501-update-aspace-oai-identifier-parsing/tests/sources/xml/test_ead.py#L86) confirms that, even with the new OAI identifier in the stubbed record, we get the same TIMDEX …
> TIMX 501 - update aspace oai identifier parsing

- tests/sources/xml/test_ead.py
- transmogrifier/sources/xml/ead.py
This PR supports an additional variation on the ASpace OAI identifier we might say.
It was believed that we would only see `oai:mit/...` (single slash) or `oai:mit//...` (double slash), but it appears we may also see `oai:mit:/` (colon + slash).  
This updated regex handles all three cases, and a dedicated unit test is added.
**NOTE**: it is known that [one test is failing in CI](https://github.com/MITLibraries/transmogrifier/actions/runs/15451334108/job/43493916766?pr=253).  It is a test that gets at something finicky around memory management with BS4 + parquet writing.  I would propose to address that failing test seperate of this PR.   Local testing, builds, and actual running in Dev/Stage/Prod has been unaffected.
NO
NO
- https://mitlibraries.atlassian.net/browse/TIMX-501
> TIMX 501 - Handle additional ASpace OAI identifier pattern
